<?php
 return array (
  6 => 
  array (
    'name' => '股票',
    'pid' => '1',
    'child' => '1',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'gupiao',
    'url' => 'http://news.wuzhicms.com/gupiao/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  7 => 
  array (
    'name' => '基金',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'jijin',
    'url' => '/index.php?v=listing&cid=7',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  8 => 
  array (
    'name' => '保险',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'baoxian',
    'url' => '/index.php?v=listing&cid=8&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  9 => 
  array (
    'name' => '家族信托',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'jiazuxintuo',
    'url' => '/index.php?v=listing&cid=9&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  14 => 
  array (
    'name' => '图片子栏目A',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'ismenu' => '1',
    'catdir' => 'tu1',
    'url' => '/index.php?v=listing&cid=14',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  15 => 
  array (
    'name' => '图片子栏目B',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'ismenu' => '1',
    'catdir' => 'tu2',
    'url' => '/index.php?v=listing&cid=15&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  18 => 
  array (
    'name' => '下载子栏目A',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'ismenu' => '1',
    'catdir' => 'downa',
    'url' => '/index.php?v=listing&cid=18&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  20 => 
  array (
    'name' => '下载子栏目B',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'ismenu' => '1',
    'catdir' => 'downb',
    'url' => '/index.php?v=listing&cid=20&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  35 => 
  array (
    'name' => '下载子栏目C',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'ismenu' => '1',
    'catdir' => 'downc',
    'url' => '/index.php?v=listing&cid=35&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  39 => 
  array (
    'name' => '兑换排行',
    'pid' => '26',
    'child' => '0',
    'modelid' => '8',
    'ismenu' => '1',
    'catdir' => 'shangpinliebiao',
    'url' => '/index.php?v=listing&cid=39&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  41 => 
  array (
    'name' => '原创',
    'pid' => '38',
    'child' => '0',
    'modelid' => '7',
    'ismenu' => '1',
    'catdir' => 'yuanchuang',
    'url' => '/index.php?v=listing&cid=41&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  42 => 
  array (
    'name' => 'MV',
    'pid' => '38',
    'child' => '0',
    'modelid' => '7',
    'ismenu' => '1',
    'catdir' => 'MV',
    'url' => '/index.php?v=listing&cid=42&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  43 => 
  array (
    'name' => '综艺',
    'pid' => '38',
    'child' => '0',
    'modelid' => '7',
    'ismenu' => '1',
    'catdir' => 'zongyi',
    'url' => '/index.php?v=listing&cid=43&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  44 => 
  array (
    'name' => '娱乐',
    'pid' => '38',
    'child' => '0',
    'modelid' => '7',
    'ismenu' => '1',
    'catdir' => 'yule',
    'url' => '/index.php?v=listing&cid=44&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  48 => 
  array (
    'name' => '单品团',
    'pid' => '27',
    'child' => '0',
    'modelid' => '2',
    'ismenu' => '1',
    'catdir' => 'danpin',
    'url' => '/index.php?v=listing&cid=48&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  49 => 
  array (
    'name' => '生活汇',
    'pid' => '26',
    'child' => '0',
    'modelid' => '8',
    'ismenu' => '1',
    'catdir' => 'shenghuohui',
    'url' => '/index.php?v=listing&cid=49&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  50 => 
  array (
    'name' => '品牌团',
    'pid' => '27',
    'child' => '0',
    'modelid' => '2',
    'ismenu' => '1',
    'catdir' => 'pinpai',
    'url' => '/index.php?v=listing&cid=50&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  52 => 
  array (
    'name' => '公司介绍',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'gongsijieshao',
    'url' => '/index.php?v=listing&cid=52&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  53 => 
  array (
    'name' => '联系我们',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'lianxiwomen',
    'url' => '/index.php?v=listing&cid=53&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  54 => 
  array (
    'name' => '用户协议',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'yonghuxieyi',
    'url' => '/index.php?v=listing&cid=54&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  55 => 
  array (
    'name' => '法律声明',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'falvshengming',
    'url' => '/index.php?v=listing&cid=55&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  56 => 
  array (
    'name' => '付款方式',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'fukuanfangshi',
    'url' => '/index.php?v=listing&cid=56&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  60 => 
  array (
    'name' => 'testaaaa',
    'pid' => '6',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'testaaaa',
    'url' => 'http://news.wuzhicms.com/gupiao/testaaaa/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  62 => 
  array (
    'name' => '生成静态',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'test_html',
    'url' => '/test_html/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '2',
    'icon' => '',
  ),
  63 => 
  array (
    'name' => '动态栏目',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'dongtailanmu',
    'url' => '/index.php?v=listing&cid=63&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '2',
    'icon' => '',
  ),
  1 => 
  array (
    'name' => '新闻',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'ismenu' => '1',
    'catdir' => 'xinwen',
    'url' => 'http://news.wuzhicms.com/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
    'domain' => 'http://news.wuzhicms.com/',
  ),
  38 => 
  array (
    'name' => '视频',
    'pid' => '0',
    'child' => '1',
    'modelid' => '7',
    'ismenu' => '1',
    'catdir' => 'shipin',
    'url' => '/index.php?v=listing&cid=38&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  3 => 
  array (
    'name' => '图片',
    'pid' => '0',
    'child' => '1',
    'modelid' => '5',
    'ismenu' => '1',
    'catdir' => 'tupian',
    'url' => '/index.php?v=listing&cid=3&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  4 => 
  array (
    'name' => '下载',
    'pid' => '0',
    'child' => '1',
    'modelid' => '6',
    'ismenu' => '1',
    'catdir' => 'xiazai',
    'url' => '/index.php?v=listing&cid=4&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  27 => 
  array (
    'name' => '团购',
    'pid' => '0',
    'child' => '1',
    'modelid' => '2',
    'ismenu' => '1',
    'catdir' => 'tuangouyanshi',
    'url' => '/index.php?v=listing&cid=27&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  26 => 
  array (
    'name' => '积分商城',
    'pid' => '0',
    'child' => '1',
    'modelid' => '8',
    'ismenu' => '1',
    'catdir' => 'jifenshangcheng',
    'url' => '/index.php?v=listing&cid=26&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  51 => 
  array (
    'name' => '关于我们',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'ismenu' => '0',
    'catdir' => 'guanyuwomen',
    'url' => '/index.php?v=listing&cid=51&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
)?>