<?php
 return array (
  1 => 
  array (
    'name' => '新闻A',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'xinwen',
    'url' => '/index.php?v=listing&cid=1&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  2 => 
  array (
    'name' => '新闻B',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'xinwenyanshi2',
    'url' => '/index.php?v=listing&cid=2&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  3 => 
  array (
    'name' => '图片演示',
    'pid' => '0',
    'child' => '1',
    'modelid' => '5',
    'catdir' => 'tupian',
    'url' => '/index.php?v=listing&cid=3&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  4 => 
  array (
    'name' => '下载演示',
    'pid' => '0',
    'child' => '1',
    'modelid' => '6',
    'catdir' => 'xiazai',
    'url' => '/index.php?v=listing&cid=4&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  31 => 
  array (
    'name' => '联系我们',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'lianxiwomen',
    'url' => '/index.php?v=listing&cid=31&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  6 => 
  array (
    'name' => '股票',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'gupiao',
    'url' => '/index.php?v=listing&cid=6&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  7 => 
  array (
    'name' => '基金',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jijin',
    'url' => '/index.php?v=listing&cid=7&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  8 => 
  array (
    'name' => '保险',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'baoxian',
    'url' => '/index.php?v=listing&cid=8&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  9 => 
  array (
    'name' => '家族信托',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiazuxintuo',
    'url' => '/index.php?v=listing&cid=9&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  10 => 
  array (
    'name' => '房地产',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'fangdichan',
    'url' => '/index.php?v=listing&cid=10&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  11 => 
  array (
    'name' => '移民',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yimin',
    'url' => '/index.php?v=listing&cid=11&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  12 => 
  array (
    'name' => '项目投资',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'xiangmutouzi',
    'url' => '/index.php?v=listing&cid=12&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  14 => 
  array (
    'name' => '图片子栏目A',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'catdir' => 'tu1',
    'url' => '/index.php?v=listing&cid=14&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  15 => 
  array (
    'name' => '图片子栏目B',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'catdir' => 'tu2',
    'url' => '/index.php?v=listing&cid=15&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  30 => 
  array (
    'name' => '关于我们',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'aboutus',
    'url' => '/index.php?v=listing&cid=30&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  18 => 
  array (
    'name' => '下载子栏目A',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downa',
    'url' => '/index.php?v=listing&cid=18&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  29 => 
  array (
    'name' => '关于我们',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'guanyuwomen',
    'url' => '/index.php?v=listing&cid=29&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  20 => 
  array (
    'name' => '下载子栏目B',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downb',
    'url' => '/index.php?v=listing&cid=20&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  32 => 
  array (
    'name' => '用户协议',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yonghuxieyi',
    'url' => '/index.php?v=listing&cid=32&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  28 => 
  array (
    'name' => '北京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '3',
    'catdir' => 'beijing',
    'url' => '/index.php?v=listing&cid=28&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  27 => 
  array (
    'name' => '团购',
    'pid' => '0',
    'child' => '0',
    'modelid' => '2',
    'catdir' => 'tuangouyanshi',
    'url' => '/index.php?v=listing&cid=27&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  26 => 
  array (
    'name' => '积分商城',
    'pid' => '0',
    'child' => '0',
    'modelid' => '8',
    'catdir' => 'jifenshangcheng',
    'url' => '/index.php?v=listing&cid=26&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  33 => 
  array (
    'name' => '法律声明',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'falvshengming',
    'url' => '/index.php?v=listing&cid=33&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  35 => 
  array (
    'name' => '下载子栏目C',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downc',
    'url' => '/index.php?v=listing&cid=35&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  36 => 
  array (
    'name' => '手机推广',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shoujituiguang',
    'url' => '/index.php?v=listing&cid=36&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  37 => 
  array (
    'name' => '微信自动回复',
    'pid' => '0',
    'child' => '0',
    'modelid' => '22',
    'catdir' => 'weixinautoreply',
    'url' => '/index.php?v=listing&cid=37&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
)?>