<?php
 return array (
  'blockid' => '12',
  'tplid' => 't2',
  'modelid' => '0',
  'siteid' => '1',
  'type' => '2',
  'codetype' => '0',
  'name' => '头部banner',
  'max_number' => '500',
  'code' => '<img src="http://placehold.it/450x75" width="450" height="75">',
  'url' => '',
  'updatetime' => '1429601931',
  'status' => '9',
  'timing' => '1429605531',
  'createhtml' => '0',
  'remark' => '',
  'isopenid' => '0',
  'lang' => 'zh',
)?>