<?php
 return array (
  'qq' => 
  array (
    'id' => '500',
    'modelid' => '10',
    'field' => 'qq',
    'name' => 'QQ',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
)?>