<?php
 return array (
  'tel' => 
  array (
    'id' => '392',
    'modelid' => '20',
    'field' => 'tel',
    'name' => '电话',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'sex' => 
  array (
    'id' => '390',
    'modelid' => '20',
    'field' => 'sex',
    'name' => '性别',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '男|1
女|0',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'truename' => 
  array (
    'id' => '391',
    'modelid' => '20',
    'field' => 'truename',
    'name' => '联系人名称',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'qytype' => 
  array (
    'id' => '389',
    'modelid' => '20',
    'field' => 'qytype',
    'name' => '企业性质',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '国有企业|1
集体所有制企业|2
联营企业|3
三资企业|4
私营企业|5
其他企业|6',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'email' => 
  array (
    'id' => '393',
    'modelid' => '20',
    'field' => 'email',
    'name' => '邮件',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'companyname' => 
  array (
    'id' => '394',
    'modelid' => '20',
    'field' => 'companyname',
    'name' => '公司名称',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'yixiang' => 
  array (
    'id' => '395',
    'modelid' => '20',
    'field' => 'yixiang',
    'name' => '意向医院',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '请选择|0
慈铭体检|49
爱康国宾|50
美年大健康|51
现代阳光|52
九华体检|53
民众体检|54
美兆体检|55
医协博尚|56
北京军区总医院|57',
      'boxtype' => 'select',
      'fieldtype' => 'smallint',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'yusuan' => 
  array (
    'id' => '396',
    'modelid' => '20',
    'field' => 'yusuan',
    'name' => '预算',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'renshu' => 
  array (
    'id' => '397',
    'modelid' => '20',
    'field' => 'renshu',
    'name' => '人数',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'tjtime' => 
  array (
    'id' => '398',
    'modelid' => '20',
    'field' => 'tjtime',
    'name' => '体检时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'province' => 
  array (
    'id' => '407',
    'modelid' => '20',
    'field' => 'province',
    'name' => '所属省',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'city' => 
  array (
    'id' => '408',
    'modelid' => '20',
    'field' => 'city',
    'name' => '所属城市',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'area' => 
  array (
    'id' => '409',
    'modelid' => '20',
    'field' => 'area',
    'name' => '所属地区',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'type' => 
  array (
    'id' => '416',
    'modelid' => '20',
    'field' => 'type',
    'name' => 'type',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '1',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'flag' => 
  array (
    'id' => '418',
    'modelid' => '20',
    'field' => 'flag',
    'name' => '需求状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '抢单中|0
待发送结果|1
已结束|2',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'cid' => 
  array (
    'id' => '335',
    'modelid' => '20',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'title' => 
  array (
    'id' => '336',
    'modelid' => '20',
    'field' => 'title',
    'name' => '标题',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'keywords' => 
  array (
    'id' => '337',
    'modelid' => '20',
    'field' => 'keywords',
    'name' => '关键词',
    'remark' => '多关键词之间用半角逗号“,”隔开',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'keyword',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'remark' => 
  array (
    'id' => '333',
    'modelid' => '20',
    'field' => 'remark',
    'name' => '摘要',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'thumb' => 
  array (
    'id' => '331',
    'modelid' => '20',
    'field' => 'thumb',
    'name' => '缩略图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'watermark' => '0',
      'isselectimage' => '1',
      'images_width' => '',
      'images_height' => '',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'block' => 
  array (
    'id' => '324',
    'modelid' => '20',
    'field' => 'block',
    'name' => '添加到推荐位',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'block',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'content' => 
  array (
    'id' => '334',
    'modelid' => '20',
    'field' => 'content',
    'name' => '其他需求',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 
    array (
      'toolbar' => 'basic',
      'defaultvalue' => '',
      'enablesaveimage' => '1',
      'watermark_enable' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '8',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'relation' => 
  array (
    'id' => '332',
    'modelid' => '20',
    'field' => 'relation',
    'name' => '相关内容',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'relation',
    'setting' => 
    array (
      'formtext' => '相关内容',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'url' => 
  array (
    'id' => '326',
    'modelid' => '20',
    'field' => 'url',
    'name' => '链接地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'url',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'addtime' => 
  array (
    'id' => '323',
    'modelid' => '20',
    'field' => 'addtime',
    'name' => '添加时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '12',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'allowcomment' => 
  array (
    'id' => '329',
    'modelid' => '20',
    'field' => 'allowcomment',
    'name' => '允许评论',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '允许|1
不允许|0',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'size' => '',
      'defaultvalue' => '1',
      'outputtype' => '0',
      'filtertype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '17',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'groups' => 
  array (
    'id' => '325',
    'modelid' => '20',
    'field' => 'groups',
    'name' => '用户组权限',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'group',
    'setting' => 
    array (
      'groups' => '4,5',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '18',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'sort' => 
  array (
    'id' => '327',
    'modelid' => '20',
    'field' => 'sort',
    'name' => '权重',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'slider',
    'setting' => 
    array (
      'defaultvalue' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '20',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'template' => 
  array (
    'id' => '328',
    'modelid' => '20',
    'field' => 'template',
    'name' => '内容页模板',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => 
    array (
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '21',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
  'status' => 
  array (
    'id' => '330',
    'modelid' => '20',
    'field' => 'status',
    'name' => '稿件状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '30',
    'disabled' => '0',
    'powerful_field' => '0',
    'workflow_field' => '0',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
  ),
)?>