<?php
 return array (
  1 => 
  array (
    'modelid' => '1',
    'm' => 'content',
    'name' => '文章模型',
    'master_table' => 'content_share',
    'attr_table' => 'news_data',
    'remark' => '',
    'template' => '',
    'css' => 'icon-file-word-o',
    'share_model' => '1',
    'manage_template' => '',
  ),
  2 => 
  array (
    'modelid' => '2',
    'm' => 'content',
    'name' => '团购',
    'master_table' => 'tuangou',
    'attr_table' => 'tuangou_data',
    'remark' => '',
    'template' => '',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
  3 => 
  array (
    'modelid' => '3',
    'm' => 'content',
    'name' => '企业库',
    'master_table' => 'mec',
    'attr_table' => 'mec_data',
    'remark' => '',
    'template' => '',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
  5 => 
  array (
    'modelid' => '5',
    'm' => 'content',
    'name' => '图片模型',
    'master_table' => 'content_share',
    'attr_table' => 'picture_data',
    'remark' => '',
    'template' => 'show',
    'css' => 'icon-file-photo-o',
    'share_model' => '1',
    'manage_template' => '',
  ),
  6 => 
  array (
    'modelid' => '6',
    'm' => 'content',
    'name' => '下载模型',
    'master_table' => 'content_share',
    'attr_table' => 'download_data',
    'remark' => '',
    'template' => 'show',
    'css' => 'icon-file-zip-o',
    'share_model' => '1',
    'manage_template' => '',
  ),
  7 => 
  array (
    'modelid' => '7',
    'm' => 'content',
    'name' => '视频模型',
    'master_table' => 'content_share',
    'attr_table' => 'video_data',
    'remark' => '',
    'template' => 'show',
    'css' => 'icon-file-movie-o',
    'share_model' => '1',
    'manage_template' => '',
  ),
  8 => 
  array (
    'modelid' => '8',
    'm' => 'content',
    'name' => '积分商城',
    'master_table' => 'point2goods',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
  20 => 
  array (
    'modelid' => '20',
    'm' => 'content',
    'name' => '公司需求模型',
    'master_table' => 'gsxq',
    'attr_table' => 'gsxq_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
  21 => 
  array (
    'modelid' => '21',
    'm' => 'content',
    'name' => '商家发布信息',
    'master_table' => 'jgfb',
    'attr_table' => 'jgfb_data',
    'remark' => '商家发布促销，活动信息',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
  22 => 
  array (
    'modelid' => '22',
    'm' => 'content',
    'name' => '微信自动回复',
    'master_table' => 'weixin_auto_reply',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => '',
  ),
)?>